// lib/mockData.ts

import type { User, Issue, Comment, StatusChange, CityStats, Notification } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    created_at: '2024-01-15T08:00:00Z',
    name: 'Айдар Сейткали',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aidar',
    role: 'citizen',
    phone: '+7 707 123 4567',
    email: 'aidar@example.com',
    city: 'Алматы',
    district: 'Алмалинский',
    points: 234,
    issues_count: 234,
    resolved_count: 0,
  },
  {
    id: 'u2',
    created_at: '2024-02-10T09:00:00Z',
    name: 'Гүлнар Ахметова',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=gulnar',
    role: 'volunteer',
    phone: '+7 701 987 6543',
    email: 'gulnar@example.com',
    city: 'Алматы',
    district: 'Медеуский',
    points: 145,
    issues_count: 12,
    resolved_count: 145,
  },
  {
    id: 'u3',
    created_at: '2024-01-20T10:00:00Z',
    name: 'Акимат Бостандыкского района',
    avatar_url: 'https://api.dicebear.com/7.x/initials/svg?seed=АБ',
    role: 'akimat',
    phone: '+7 727 000 0001',
    email: 'bostanyk@almaty.gov.kz',
    city: 'Алматы',
    district: 'Бостандыкский',
    points: 0,
    issues_count: 0,
    resolved_count: 87,
  },
  {
    id: 'u4',
    created_at: '2024-03-05T11:00:00Z',
    name: 'Нурлан Бекенов',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nurlan',
    role: 'citizen',
    phone: '+7 705 555 1234',
    email: null,
    city: 'Астана',
    district: 'Есильский',
    points: 67,
    issues_count: 67,
    resolved_count: 0,
  },
  {
    id: 'u5',
    created_at: '2024-02-28T12:00:00Z',
    name: 'Дина Жакупова',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dina',
    role: 'volunteer',
    phone: '+7 702 444 5678',
    email: 'dina@example.com',
    city: 'Астана',
    district: 'Алматинский',
    points: 38,
    issues_count: 5,
    resolved_count: 38,
  },
  {
    id: 'u6',
    created_at: '2024-04-01T08:00:00Z',
    name: 'Серік Омаров',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=serik',
    role: 'citizen',
    phone: '+7 708 333 9876',
    email: 'serik@example.com',
    city: 'Алматы',
    district: 'Жетысуский',
    points: 18,
    issues_count: 18,
    resolved_count: 0,
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'i1',
    created_at: '2025-05-20T10:30:00Z',
    updated_at: '2025-05-25T14:00:00Z',
    title: 'Огромная яма на проезжей части',
    description: 'На пересечении улиц Абая и Достык огромная яма. Уже несколько машин повредили шины. Опасно для водителей и велосипедистов.',
    category: 'roads',
    danger_level: 'dangerous',
    status: 'in_progress',
    assigned_to: 'akimat',
    photos: [
      'https://images.unsplash.com/photo-1584267385494-9fdd9a71ad75?w=600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    ],
    video_url: null,
    lat: 43.2364,
    lng: 76.9457,
    address: 'ул. Абая / ул. Достык',
    city: 'Алматы',
    district: 'Медеуский',
    author_id: 'u1',
    author: MOCK_USERS[0],
    confirmations: 47,
    likes: 89,
    comments_count: 12,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i2',
    created_at: '2025-05-22T08:15:00Z',
    updated_at: '2025-05-22T08:15:00Z',
    title: 'Не работают фонари на пешеходном переходе',
    description: 'Три фонаря подряд не горят на переходе у школы №47. Дети переходят дорогу в темноте, очень опасно.',
    category: 'lighting',
    danger_level: 'critical',
    status: 'new',
    assigned_to: 'both',
    photos: [
      'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600',
    ],
    video_url: null,
    lat: 43.2480,
    lng: 76.8940,
    address: 'ул. Тимирязева, 47 (у школы №47)',
    city: 'Алматы',
    district: 'Алмалинский',
    author_id: 'u6',
    author: MOCK_USERS[5],
    confirmations: 23,
    likes: 41,
    comments_count: 5,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i3',
    created_at: '2025-05-18T16:40:00Z',
    updated_at: '2025-05-30T11:00:00Z',
    title: 'Незаконная свалка в парке',
    description: 'В парке Горького за кустами выросла стихийная свалка. Мусор лежит уже больше двух недель, никто не убирает.',
    category: 'trash',
    danger_level: 'moderate',
    status: 'done',
    assigned_to: 'volunteers',
    photos: [
      'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=600',
    ],
    video_url: null,
    lat: 43.2220,
    lng: 76.9280,
    address: 'Парк Горького, за центральной аллеей',
    city: 'Алматы',
    district: 'Бостандыкский',
    author_id: 'u1',
    author: MOCK_USERS[0],
    confirmations: 31,
    likes: 56,
    comments_count: 8,
    resolved_at: '2025-05-30T11:00:00Z',
    resolver_id: 'u2',
  },
  {
    id: 'i4',
    created_at: '2025-05-25T09:00:00Z',
    updated_at: '2025-05-26T10:00:00Z',
    title: 'Сломана детская горка на площадке',
    description: 'На детской площадке во дворе дома по пр. Назарбаева 28 сломана горка. Острые края металла, ребёнок может пораниться.',
    category: 'children',
    danger_level: 'dangerous',
    status: 'reviewing',
    assigned_to: 'akimat',
    photos: [
      'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=600',
    ],
    video_url: null,
    lat: 43.2550,
    lng: 76.9100,
    address: 'пр. Назарбаева, 28, двор',
    city: 'Алматы',
    district: 'Алмалинский',
    author_id: 'u6',
    author: MOCK_USERS[5],
    confirmations: 15,
    likes: 28,
    comments_count: 3,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i5',
    created_at: '2025-05-10T07:30:00Z',
    updated_at: '2025-05-10T07:30:00Z',
    title: 'Прорыв трубы — вода заливает тротуар',
    description: 'На ул. Кунаева прорвало трубу горячего водоснабжения. Вода хлещет на тротуар, образовалась большая лужа, пар поднимается.',
    category: 'water',
    danger_level: 'critical',
    status: 'new',
    assigned_to: 'akimat',
    photos: [
      'https://images.unsplash.com/photo-1585858229735-cd08d8cb510d?w=600',
    ],
    video_url: null,
    lat: 43.2600,
    lng: 76.9450,
    address: 'ул. Кунаева, 12',
    city: 'Алматы',
    district: 'Медеуский',
    author_id: 'u1',
    author: MOCK_USERS[0],
    confirmations: 62,
    likes: 104,
    comments_count: 19,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i6',
    created_at: '2025-05-28T13:00:00Z',
    updated_at: '2025-05-28T13:00:00Z',
    title: 'Стая агрессивных собак у рынка',
    description: 'Возле Зелёного базара стая из 6-7 бездомных собак. Нападают на прохожих, особенно опасно для детей.',
    category: 'animals',
    danger_level: 'dangerous',
    status: 'new',
    assigned_to: 'both',
    photos: [],
    video_url: null,
    lat: 43.2530,
    lng: 76.9390,
    address: 'Зелёный базар, южный вход',
    city: 'Алматы',
    district: 'Алмалинский',
    author_id: 'u6',
    author: MOCK_USERS[5],
    confirmations: 34,
    likes: 45,
    comments_count: 7,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i7',
    created_at: '2025-05-15T11:20:00Z',
    updated_at: '2025-05-29T16:00:00Z',
    title: 'Разбитый тротуар у автобусной остановки',
    description: 'Весь тротуар около остановки «Байтерек» в плиточных ямах. Люди спотыкаются, пожилым очень сложно ходить.',
    category: 'transport',
    danger_level: 'moderate',
    status: 'in_progress',
    assigned_to: 'akimat',
    photos: [
      'https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?w=600',
    ],
    video_url: null,
    lat: 51.1280,
    lng: 71.4300,
    address: 'Остановка «Байтерек», пр. Нурсултан',
    city: 'Астана',
    district: 'Есильский',
    author_id: 'u4',
    author: MOCK_USERS[3],
    confirmations: 28,
    likes: 51,
    comments_count: 6,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i8',
    created_at: '2025-05-19T09:45:00Z',
    updated_at: '2025-06-01T10:00:00Z',
    title: 'Заброшенное дерево перегораживает дорогу',
    description: 'После бури упало большое дерево и лежит поперёк тротуара на ул. Достык. Люди ходят по проезжей части.',
    category: 'greenery',
    danger_level: 'dangerous',
    status: 'done',
    assigned_to: 'volunteers',
    photos: [
      'https://images.unsplash.com/photo-1621197025978-29d49d0c10f7?w=600',
    ],
    video_url: null,
    lat: 51.1350,
    lng: 71.4050,
    address: 'ул. Достык, 5 (у дома)',
    city: 'Астана',
    district: 'Алматинский',
    author_id: 'u4',
    author: MOCK_USERS[3],
    confirmations: 19,
    likes: 33,
    comments_count: 4,
    resolved_at: '2025-06-01T10:00:00Z',
    resolver_id: 'u5',
  },
  {
    id: 'i9',
    created_at: '2025-06-01T08:00:00Z',
    updated_at: '2025-06-01T08:00:00Z',
    title: 'Трещина в фасаде жилого дома',
    description: 'На фасаде 9-этажного дома по ул. Сейфуллина появилась вертикальная трещина. Жильцы беспокоятся о безопасности здания.',
    category: 'buildings',
    danger_level: 'moderate',
    status: 'new',
    assigned_to: 'akimat',
    photos: [
      'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=600',
    ],
    video_url: null,
    lat: 51.1800,
    lng: 71.4470,
    address: 'ул. Сейфуллина, 18',
    city: 'Астана',
    district: 'Есильский',
    author_id: 'u4',
    author: MOCK_USERS[3],
    confirmations: 8,
    likes: 14,
    comments_count: 2,
    resolved_at: null,
    resolver_id: null,
  },
  {
    id: 'i10',
    created_at: '2025-06-05T14:30:00Z',
    updated_at: '2025-06-05T14:30:00Z',
    title: 'Не работают качели на площадке',
    description: 'В сквере на пр. Республики не работают оба качели — цепи оборваны. Дети не могут играть.',
    category: 'children',
    danger_level: 'minor',
    status: 'new',
    assigned_to: 'volunteers',
    photos: [],
    video_url: null,
    lat: 51.1600,
    lng: 71.4700,
    address: 'пр. Республики, сквер у д.22',
    city: 'Астана',
    district: 'Алматинский',
    author_id: 'u5',
    author: MOCK_USERS[4],
    confirmations: 5,
    likes: 9,
    comments_count: 1,
    resolved_at: null,
    resolver_id: null,
  },
  // Шымкент
  {
    id: 'i11',
    created_at: '2025-06-08T10:00:00Z',
    updated_at: '2025-06-08T10:00:00Z',
    title: 'Сгоревший мусорный контейнер',
    description: 'На ул. Байтурсынова сгорел контейнер для ТБО. Металлический каркас торчит посреди тротуара, прохожие обходят по дороге.',
    category: 'trash',
    danger_level: 'moderate',
    status: 'new',
    assigned_to: 'akimat',
    photos: [],
    video_url: null,
    lat: 42.3170,
    lng: 69.5900,
    address: 'ул. Байтурсынова, 14',
    city: 'Шымкент',
    district: 'Аль-Фарабийский',
    author_id: 'u6',
    author: MOCK_USERS[5],
    confirmations: 11,
    likes: 19,
    comments_count: 2,
    resolved_at: null,
    resolver_id: null,
  },
  // Костанай
  {
    id: 'i12',
    created_at: '2025-06-10T08:30:00Z',
    updated_at: '2025-06-10T08:30:00Z',
    title: 'Разбитый фонарь у пешеходного перехода',
    description: 'Фонарный столб у перехода возле школы №23 наклонился после ДТП. Провод свисает низко — угроза поражения током.',
    category: 'lighting',
    danger_level: 'critical',
    status: 'reviewing',
    assigned_to: 'akimat',
    photos: [],
    video_url: null,
    lat: 53.2144,
    lng: 63.6240,
    address: 'ул. Баймагамбетова, у школы №23',
    city: 'Костанай',
    district: 'Костанайский',
    author_id: 'u4',
    author: MOCK_USERS[3],
    confirmations: 22,
    likes: 37,
    comments_count: 4,
    resolved_at: null,
    resolver_id: null,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    created_at: '2025-05-21T09:00:00Z',
    issue_id: 'i1',
    author_id: 'u2',
    author: MOCK_USERS[1],
    text: 'Видела это место вчера, яма действительно огромная. Я сама объехала её с трудом.',
    photos: [],
  },
  {
    id: 'c2',
    created_at: '2025-05-22T11:30:00Z',
    issue_id: 'i1',
    author_id: 'u3',
    author: MOCK_USERS[2],
    text: 'Заявка принята. Бригада дорожного ремонта запланирована на 26 мая.',
    photos: [],
  },
  {
    id: 'c3',
    created_at: '2025-05-26T16:00:00Z',
    issue_id: 'i1',
    author_id: 'u3',
    author: MOCK_USERS[2],
    text: 'Ремонт начат. Завершение ожидается 28 мая.',
    photos: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600'],
  },
];

export const MOCK_STATUS_CHANGES: StatusChange[] = [
  {
    id: 'sc1',
    created_at: '2025-05-22T11:30:00Z',
    issue_id: 'i1',
    old_status: 'new',
    new_status: 'reviewing',
    changed_by: 'u3',
    changed_by_user: MOCK_USERS[2],
    note: 'Акимат взял заявку в работу',
  },
  {
    id: 'sc2',
    created_at: '2025-05-26T16:00:00Z',
    issue_id: 'i1',
    old_status: 'reviewing',
    new_status: 'in_progress',
    changed_by: 'u3',
    changed_by_user: MOCK_USERS[2],
    note: 'Начат ремонт дорожного покрытия',
  },
];

export const MOCK_STATS: CityStats[] = [
  {
    city: 'Алматы',
    total: 6,
    resolved: 1,
    in_progress: 2,
    avg_resolution_days: 8,
    top_categories: [
      { category: 'roads', count: 2 },
      { category: 'lighting', count: 1 },
      { category: 'trash', count: 1 },
      { category: 'children', count: 1 },
      { category: 'animals', count: 1 },
    ],
  },
  {
    city: 'Астана',
    total: 4,
    resolved: 1,
    in_progress: 1,
    avg_resolution_days: 5,
    top_categories: [
      { category: 'transport', count: 1 },
      { category: 'greenery', count: 1 },
      { category: 'buildings', count: 1 },
      { category: 'children', count: 1 },
    ],
  },
  {
    city: 'Шымкент',
    total: 1,
    resolved: 0,
    in_progress: 0,
    avg_resolution_days: 0,
    top_categories: [
      { category: 'trash', count: 1 },
    ],
  },
  {
    city: 'Костанай',
    total: 1,
    resolved: 0,
    in_progress: 0,
    avg_resolution_days: 0,
    top_categories: [
      { category: 'lighting', count: 1 },
    ],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    created_at: '2025-05-26T16:00:00Z',
    user_id: 'u1',
    issue_id: 'i1',
    issue_title: 'Огромная яма на проезжей части',
    type: 'status_change',
    read: false,
    message_ru: 'Статус вашей заявки изменён: В процессе',
    message_en: 'Your issue status changed: In Progress',
  },
  {
    id: 'n2',
    created_at: '2025-05-22T11:30:00Z',
    user_id: 'u1',
    issue_id: 'i1',
    issue_title: 'Огромная яма на проезжей части',
    type: 'new_comment',
    read: true,
    message_ru: 'Акимат оставил комментарий к вашей заявке',
    message_en: 'Akimat left a comment on your issue',
  },
  {
    id: 'n3',
    created_at: '2025-06-01T08:00:00Z',
    user_id: 'u2',
    issue_id: 'i9',
    issue_title: 'Трещина в фасаде жилого дома',
    type: 'new_issue',
    read: false,
    message_ru: 'Новая заявка в вашем районе',
    message_en: 'New issue in your area',
  },
];

export function getCitizenRank(points: number) {
  const ranks = [
    { emoji: '👑', labelRu: 'Легенда улиц', labelEn: 'Street Legend', min: 200 },
    { emoji: '🌆', labelRu: 'Страж города', labelEn: 'City Guardian', min: 100 },
    { emoji: '🏙️', labelRu: 'Голос района', labelEn: 'District Voice', min: 50 },
    { emoji: '🔦', labelRu: 'Дозорный', labelEn: 'Watcher', min: 30 },
    { emoji: '📡', labelRu: 'Сигнальщик', labelEn: 'Signaller', min: 15 },
    { emoji: '🗺️', labelRu: 'Картограф', labelEn: 'Cartographer', min: 5 },
    { emoji: '👁️', labelRu: 'Наблюдатель', labelEn: 'Observer', min: 0 },
  ];
  return ranks.find(r => points >= r.min)!;
}

export function getVolunteerRank(points: number) {
  const ranks = [
    { emoji: '💎', labelRu: 'Элита квартала', labelEn: 'Quarter Elite', min: 200 },
    { emoji: '🏆', labelRu: 'Народный герой', labelEn: "People's Hero", min: 100 },
    { emoji: '🛡️', labelRu: 'Защитник города', labelEn: 'City Defender', min: 50 },
    { emoji: '🦺', labelRu: 'Человек района', labelEn: 'District Person', min: 30 },
    { emoji: '🛠️', labelRu: 'Полевой агент', labelEn: 'Field Agent', min: 15 },
    { emoji: '🔧', labelRu: 'Мастер дела', labelEn: 'Master', min: 5 },
    { emoji: '🤝', labelRu: 'Новобранец', labelEn: 'Recruit', min: 0 },
  ];
  return ranks.find(r => points >= r.min)!;
}
